export interface CountryCode {
  name: string
  iso: string
  dial: string
  /** [min, max] digits expected in the national number, excluding the dial code */
  len: [number, number]
}

/** Generic fallback range for countries without a confidently-known fixed length. */
const DEFAULT_LEN: [number, number] = [6, 14]

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Afghanistan', iso: 'AF', dial: '+93', len: DEFAULT_LEN },
  { name: 'Albania', iso: 'AL', dial: '+355', len: DEFAULT_LEN },
  { name: 'Algeria', iso: 'DZ', dial: '+213', len: DEFAULT_LEN },
  { name: 'Andorra', iso: 'AD', dial: '+376', len: DEFAULT_LEN },
  { name: 'Angola', iso: 'AO', dial: '+244', len: DEFAULT_LEN },
  { name: 'Argentina', iso: 'AR', dial: '+54', len: [10, 11] },
  { name: 'Armenia', iso: 'AM', dial: '+374', len: DEFAULT_LEN },
  { name: 'Australia', iso: 'AU', dial: '+61', len: [9, 9] },
  { name: 'Austria', iso: 'AT', dial: '+43', len: DEFAULT_LEN },
  { name: 'Azerbaijan', iso: 'AZ', dial: '+994', len: DEFAULT_LEN },
  { name: 'Bahamas', iso: 'BS', dial: '+1242', len: [7, 7] },
  { name: 'Bahrain', iso: 'BH', dial: '+973', len: [8, 8] },
  { name: 'Bangladesh', iso: 'BD', dial: '+880', len: [10, 10] },
  { name: 'Belarus', iso: 'BY', dial: '+375', len: DEFAULT_LEN },
  { name: 'Belgium', iso: 'BE', dial: '+32', len: [9, 9] },
  { name: 'Belize', iso: 'BZ', dial: '+501', len: DEFAULT_LEN },
  { name: 'Benin', iso: 'BJ', dial: '+229', len: DEFAULT_LEN },
  { name: 'Bhutan', iso: 'BT', dial: '+975', len: DEFAULT_LEN },
  { name: 'Bolivia', iso: 'BO', dial: '+591', len: [8, 8] },
  { name: 'Bosnia and Herzegovina', iso: 'BA', dial: '+387', len: DEFAULT_LEN },
  { name: 'Botswana', iso: 'BW', dial: '+267', len: DEFAULT_LEN },
  { name: 'Brazil', iso: 'BR', dial: '+55', len: [10, 11] },
  { name: 'Brunei', iso: 'BN', dial: '+673', len: [7, 7] },
  { name: 'Bulgaria', iso: 'BG', dial: '+359', len: DEFAULT_LEN },
  { name: 'Burkina Faso', iso: 'BF', dial: '+226', len: DEFAULT_LEN },
  { name: 'Burundi', iso: 'BI', dial: '+257', len: DEFAULT_LEN },
  { name: 'Cambodia', iso: 'KH', dial: '+855', len: DEFAULT_LEN },
  { name: 'Cameroon', iso: 'CM', dial: '+237', len: [9, 9] },
  { name: 'Canada', iso: 'CA', dial: '+1', len: [10, 10] },
  { name: 'Chad', iso: 'TD', dial: '+235', len: DEFAULT_LEN },
  { name: 'Chile', iso: 'CL', dial: '+56', len: [9, 9] },
  { name: 'China', iso: 'CN', dial: '+86', len: [11, 11] },
  { name: 'Colombia', iso: 'CO', dial: '+57', len: [10, 10] },
  { name: 'Costa Rica', iso: 'CR', dial: '+506', len: [8, 8] },
  { name: 'Croatia', iso: 'HR', dial: '+385', len: DEFAULT_LEN },
  { name: 'Cuba', iso: 'CU', dial: '+53', len: DEFAULT_LEN },
  { name: 'Cyprus', iso: 'CY', dial: '+357', len: [8, 8] },
  { name: 'Czech Republic', iso: 'CZ', dial: '+420', len: [9, 9] },
  { name: 'Denmark', iso: 'DK', dial: '+45', len: [8, 8] },
  { name: 'Dominican Republic', iso: 'DO', dial: '+1809', len: [7, 7] },
  { name: 'Ecuador', iso: 'EC', dial: '+593', len: [9, 9] },
  { name: 'Egypt', iso: 'EG', dial: '+20', len: [10, 10] },
  { name: 'El Salvador', iso: 'SV', dial: '+503', len: [8, 8] },
  { name: 'Estonia', iso: 'EE', dial: '+372', len: DEFAULT_LEN },
  { name: 'Ethiopia', iso: 'ET', dial: '+251', len: [9, 9] },
  { name: 'Fiji', iso: 'FJ', dial: '+679', len: DEFAULT_LEN },
  { name: 'Finland', iso: 'FI', dial: '+358', len: DEFAULT_LEN },
  { name: 'France', iso: 'FR', dial: '+33', len: [9, 9] },
  { name: 'Gabon', iso: 'GA', dial: '+241', len: DEFAULT_LEN },
  { name: 'Gambia', iso: 'GM', dial: '+220', len: DEFAULT_LEN },
  { name: 'Georgia', iso: 'GE', dial: '+995', len: DEFAULT_LEN },
  { name: 'Germany', iso: 'DE', dial: '+49', len: [7, 11] },
  { name: 'Ghana', iso: 'GH', dial: '+233', len: [9, 9] },
  { name: 'Greece', iso: 'GR', dial: '+30', len: [10, 10] },
  { name: 'Guatemala', iso: 'GT', dial: '+502', len: [8, 8] },
  { name: 'Guyana', iso: 'GY', dial: '+592', len: DEFAULT_LEN },
  { name: 'Haiti', iso: 'HT', dial: '+509', len: [8, 8] },
  { name: 'Honduras', iso: 'HN', dial: '+504', len: [8, 8] },
  { name: 'Hong Kong', iso: 'HK', dial: '+852', len: [8, 8] },
  { name: 'Hungary', iso: 'HU', dial: '+36', len: [9, 9] },
  { name: 'Iceland', iso: 'IS', dial: '+354', len: [7, 7] },
  { name: 'India', iso: 'IN', dial: '+91', len: [10, 10] },
  { name: 'Indonesia', iso: 'ID', dial: '+62', len: [9, 12] },
  { name: 'Iran', iso: 'IR', dial: '+98', len: [10, 10] },
  { name: 'Iraq', iso: 'IQ', dial: '+964', len: [10, 10] },
  { name: 'Ireland', iso: 'IE', dial: '+353', len: [9, 9] },
  { name: 'Israel', iso: 'IL', dial: '+972', len: [9, 9] },
  { name: 'Italy', iso: 'IT', dial: '+39', len: [9, 10] },
  { name: 'Jamaica', iso: 'JM', dial: '+1876', len: [7, 7] },
  { name: 'Japan', iso: 'JP', dial: '+81', len: [9, 10] },
  { name: 'Jordan', iso: 'JO', dial: '+962', len: [9, 9] },
  { name: 'Kazakhstan', iso: 'KZ', dial: '+7', len: [10, 10] },
  { name: 'Kenya', iso: 'KE', dial: '+254', len: [9, 9] },
  { name: 'Kuwait', iso: 'KW', dial: '+965', len: [8, 8] },
  { name: 'Kyrgyzstan', iso: 'KG', dial: '+996', len: DEFAULT_LEN },
  { name: 'Laos', iso: 'LA', dial: '+856', len: DEFAULT_LEN },
  { name: 'Latvia', iso: 'LV', dial: '+371', len: [8, 8] },
  { name: 'Lebanon', iso: 'LB', dial: '+961', len: [7, 8] },
  { name: 'Lesotho', iso: 'LS', dial: '+266', len: DEFAULT_LEN },
  { name: 'Liberia', iso: 'LR', dial: '+231', len: DEFAULT_LEN },
  { name: 'Libya', iso: 'LY', dial: '+218', len: DEFAULT_LEN },
  { name: 'Liechtenstein', iso: 'LI', dial: '+423', len: DEFAULT_LEN },
  { name: 'Lithuania', iso: 'LT', dial: '+370', len: [8, 8] },
  { name: 'Luxembourg', iso: 'LU', dial: '+352', len: DEFAULT_LEN },
  { name: 'Macau', iso: 'MO', dial: '+853', len: [8, 8] },
  { name: 'Madagascar', iso: 'MG', dial: '+261', len: DEFAULT_LEN },
  { name: 'Malawi', iso: 'MW', dial: '+265', len: DEFAULT_LEN },
  { name: 'Malaysia', iso: 'MY', dial: '+60', len: [9, 10] },
  { name: 'Maldives', iso: 'MV', dial: '+960', len: [7, 7] },
  { name: 'Mali', iso: 'ML', dial: '+223', len: DEFAULT_LEN },
  { name: 'Malta', iso: 'MT', dial: '+356', len: [8, 8] },
  { name: 'Mauritius', iso: 'MU', dial: '+230', len: DEFAULT_LEN },
  { name: 'Mexico', iso: 'MX', dial: '+52', len: [10, 10] },
  { name: 'Moldova', iso: 'MD', dial: '+373', len: DEFAULT_LEN },
  { name: 'Monaco', iso: 'MC', dial: '+377', len: DEFAULT_LEN },
  { name: 'Mongolia', iso: 'MN', dial: '+976', len: [8, 8] },
  { name: 'Montenegro', iso: 'ME', dial: '+382', len: DEFAULT_LEN },
  { name: 'Morocco', iso: 'MA', dial: '+212', len: [9, 9] },
  { name: 'Mozambique', iso: 'MZ', dial: '+258', len: DEFAULT_LEN },
  { name: 'Myanmar', iso: 'MM', dial: '+95', len: DEFAULT_LEN },
  { name: 'Namibia', iso: 'NA', dial: '+264', len: DEFAULT_LEN },
  { name: 'Nepal', iso: 'NP', dial: '+977', len: [10, 10] },
  { name: 'Netherlands', iso: 'NL', dial: '+31', len: [9, 9] },
  { name: 'New Zealand', iso: 'NZ', dial: '+64', len: [8, 9] },
  { name: 'Nicaragua', iso: 'NI', dial: '+505', len: [8, 8] },
  { name: 'Niger', iso: 'NE', dial: '+227', len: DEFAULT_LEN },
  { name: 'Nigeria', iso: 'NG', dial: '+234', len: [10, 10] },
  { name: 'North Macedonia', iso: 'MK', dial: '+389', len: DEFAULT_LEN },
  { name: 'Norway', iso: 'NO', dial: '+47', len: [8, 8] },
  { name: 'Oman', iso: 'OM', dial: '+968', len: [8, 8] },
  { name: 'Pakistan', iso: 'PK', dial: '+92', len: [10, 10] },
  { name: 'Panama', iso: 'PA', dial: '+507', len: [7, 8] },
  { name: 'Papua New Guinea', iso: 'PG', dial: '+675', len: DEFAULT_LEN },
  { name: 'Paraguay', iso: 'PY', dial: '+595', len: [9, 9] },
  { name: 'Peru', iso: 'PE', dial: '+51', len: [9, 9] },
  { name: 'Philippines', iso: 'PH', dial: '+63', len: [10, 10] },
  { name: 'Poland', iso: 'PL', dial: '+48', len: [9, 9] },
  { name: 'Portugal', iso: 'PT', dial: '+351', len: [9, 9] },
  { name: 'Qatar', iso: 'QA', dial: '+974', len: [8, 8] },
  { name: 'Romania', iso: 'RO', dial: '+40', len: [9, 9] },
  { name: 'Russia', iso: 'RU', dial: '+7', len: [10, 10] },
  { name: 'Rwanda', iso: 'RW', dial: '+250', len: [9, 9] },
  { name: 'Saudi Arabia', iso: 'SA', dial: '+966', len: [9, 9] },
  { name: 'Senegal', iso: 'SN', dial: '+221', len: [9, 9] },
  { name: 'Serbia', iso: 'RS', dial: '+381', len: DEFAULT_LEN },
  { name: 'Singapore', iso: 'SG', dial: '+65', len: [8, 8] },
  { name: 'Slovakia', iso: 'SK', dial: '+421', len: [9, 9] },
  { name: 'Slovenia', iso: 'SI', dial: '+386', len: [8, 8] },
  { name: 'Somalia', iso: 'SO', dial: '+252', len: DEFAULT_LEN },
  { name: 'South Africa', iso: 'ZA', dial: '+27', len: [9, 9] },
  { name: 'South Korea', iso: 'KR', dial: '+82', len: [9, 10] },
  { name: 'South Sudan', iso: 'SS', dial: '+211', len: DEFAULT_LEN },
  { name: 'Spain', iso: 'ES', dial: '+34', len: [9, 9] },
  { name: 'Sri Lanka', iso: 'LK', dial: '+94', len: [9, 9] },
  { name: 'Sudan', iso: 'SD', dial: '+249', len: DEFAULT_LEN },
  { name: 'Suriname', iso: 'SR', dial: '+597', len: DEFAULT_LEN },
  { name: 'Sweden', iso: 'SE', dial: '+46', len: [7, 9] },
  { name: 'Switzerland', iso: 'CH', dial: '+41', len: [9, 9] },
  { name: 'Syria', iso: 'SY', dial: '+963', len: [9, 9] },
  { name: 'Taiwan', iso: 'TW', dial: '+886', len: [9, 9] },
  { name: 'Tajikistan', iso: 'TJ', dial: '+992', len: DEFAULT_LEN },
  { name: 'Tanzania', iso: 'TZ', dial: '+255', len: [9, 9] },
  { name: 'Thailand', iso: 'TH', dial: '+66', len: [9, 9] },
  { name: 'Togo', iso: 'TG', dial: '+228', len: DEFAULT_LEN },
  { name: 'Trinidad and Tobago', iso: 'TT', dial: '+1868', len: [7, 7] },
  { name: 'Tunisia', iso: 'TN', dial: '+216', len: [8, 8] },
  { name: 'Turkey', iso: 'TR', dial: '+90', len: [10, 10] },
  { name: 'Turkmenistan', iso: 'TM', dial: '+993', len: DEFAULT_LEN },
  { name: 'Uganda', iso: 'UG', dial: '+256', len: [9, 9] },
  { name: 'Ukraine', iso: 'UA', dial: '+380', len: [9, 9] },
  { name: 'United Arab Emirates', iso: 'AE', dial: '+971', len: [9, 9] },
  { name: 'United Kingdom', iso: 'GB', dial: '+44', len: [10, 10] },
  { name: 'United States', iso: 'US', dial: '+1', len: [10, 10] },
  { name: 'Uruguay', iso: 'UY', dial: '+598', len: [8, 8] },
  { name: 'Uzbekistan', iso: 'UZ', dial: '+998', len: [9, 9] },
  { name: 'Venezuela', iso: 'VE', dial: '+58', len: [10, 10] },
  { name: 'Vietnam', iso: 'VN', dial: '+84', len: [9, 10] },
  { name: 'Yemen', iso: 'YE', dial: '+967', len: DEFAULT_LEN },
  { name: 'Zambia', iso: 'ZM', dial: '+260', len: [9, 9] },
  { name: 'Zimbabwe', iso: 'ZW', dial: '+263', len: DEFAULT_LEN },
]
